# Generated by Django 5.1.6 on 2025-02-12 19:07

import ServiceApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0002_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', validators=[ServiceApp.models.validate_file_size])),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', validators=[ServiceApp.models.validate_file_size])),
                ('description', models.TextField()),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subservices', to='ServiceApp.services')),
            ],
        ),
    ]
