# Generated by Django 5.1.6 on 2025-02-15 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0004_employeeregistration_bookinglist_serviceregistry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('VERY_BAD', 'Very Bad'), ('BAD', 'Bad'), ('GOOD', 'Good'), ('VERY_GOOD', 'Very Good'), ('EXCELLENT', 'Excellent')], default='GOOD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('select_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_ratings', to='ServiceApp.services')),
                ('select_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_ratings', to='ServiceApp.employeeregistration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
