# Generated by Django 5.1.6 on 2025-02-15 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0005_ratingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmodel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceApp.employeeregistration'),
        ),
    ]
