# Generated by Django 5.1.6 on 2025-02-15 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0006_alter_ratingmodel_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratingmodel',
            unique_together={('user', 'select_employee', 'select_service')},
        ),
        migrations.AddField(
            model_name='ratingmodel',
            name='select_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_ratings', to='ServiceApp.employeeregistration'),
        ),
        migrations.AddField(
            model_name='ratingmodel',
            name='select_service',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_ratings', to='ServiceApp.services'),
        ),
        migrations.RemoveField(
            model_name='ratingmodel',
            name='service',
        ),
    ]
