# Generated by Django 5.1.6 on 2025-02-12 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0003_services_subservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('age', models.PositiveIntegerField()),
                ('phonne_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(default='Employee', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='BookingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceApp.userprofile')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceApp.employeeregistration')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.PositiveIntegerField()),
                ('max_price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceApp.employeeregistration')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceApp.services')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('from_time', models.DateTimeField()),
                ('to_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceApp.serviceregistry')),
            ],
        ),
    ]
